# Name of the C++ compiler.
CXX = mpic++

# Compiler flags including optimization and openMP support.
CXXFLAGS = -O3 -Wall -std=c++20 -fPIC

# Compiler flags specific for the Python library.
CXXFLAGS_LIB = $(CXXFLAGS) -shared -fPIC $$(python3 -m pybind11 --includes)

# External libraries and include files. In this case this is "spglib".
LIBS = -lsymspg -lm
INCS = 

#SPGLIB_ROOT = /home/mcallsen/miniconda3/envs/forcefield_ml/lib/python3.13/site-packages/spglib

#LIBS = -L/home/mcallsen/lib -lsymspg -lm
#INCS = -I${SPGLIB_ROOT}/include
